# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a215930a7ac39a25df8ab01efd31338c24691de60ff7b50a368fa6231db7fee429e2216193708353b90bd159fc478d81030be391df671bb284bed218adbc7959

test:
  secret_key_base: c768cbbdc9e01ddc017314ebcc71d387c33a9b02df65505d1cf18737a4b61ac8cd47886e1c8a9c8624d507f2e400de17e2f1f7b2731fe55863d1491f28a57043

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
